# Generated by Django 5.2.5 on 2025-08-14 07:54

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_used", models.CharField(max_length=255)),
                ("template_version", models.CharField(blank=True, max_length=50)),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/imports/%Y/%m/%d/"
                    ),
                ),
                ("file_sha256", models.CharField(blank=True, max_length=64)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_message", models.TextField(blank=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("accepted_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("reprocess_count", models.PositiveIntegerField(default=0)),
                ("last_reprocess_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_json", models.JSONField()),
                ("normalized_data", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                            ("processed", "Processed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_details", models.TextField(blank=True)),
                ("action_taken", models.CharField(blank=True, max_length=255)),
                ("related_app_label", models.CharField(blank=True, max_length=100)),
                ("related_model", models.CharField(blank=True, max_length=100)),
                ("related_object_pk", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("retried", models.BooleanField(default=False)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="importing.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["status", "received_at"], name="importing_i_status_9c2a86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importbatch",
            index=models.Index(
                fields=["template_used"], name="importing_i_templat_56a864_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("file_sha256",), name="uq_import_batches_sha256"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=models.Index(
                fields=["batch", "status"], name="importing_i_batch_i_6b964f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="importrow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["raw_json"], name="gin_raw_json"
            ),
        ),
        migrations.AddConstraint(
            model_name="importrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="uq_batch_row_number"
            ),
        ),
    ]
