export default function Dashboard() {
  return (
    <>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></link>

      <div>
        <div className="text-xl font-bold">Welcome to SafeTracker!</div>
        <div>The content of this page is just a placeholder generated by AI.</div>
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
        <div className="rounded-lg bg-white p-6 shadow">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-500">Total Employees</p>
              <h3 className="text-2xl font-bold text-gray-800">1,248</h3>
            </div>
            <div className="rounded-full bg-blue-100 p-3 text-blue-600">
              <i className="fas fa-users text-xl"></i>
            </div>
          </div>
        </div>
        <div className="rounded-lg bg-white p-6 shadow">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-500">Total Trainings</p>
              <h3 className="text-2xl font-bold text-gray-800">24</h3>
            </div>
            <div className="rounded-full bg-green-100 p-3 text-green-600">
              <i className="fas fa-certificate text-xl"></i>
            </div>
          </div>
        </div>
        <div className="rounded-lg bg-white p-6 shadow">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-500">Completion Rate</p>
              <h3 className="text-2xl font-bold text-gray-800">78%</h3>
            </div>
            <div className="relative h-12 w-12">
              <svg className="h-full w-full" viewBox="0 0 36 36">
                <path
                  d="M18 2.0845
                                        a 15.9155 15.9155 0 0 1 0 31.831
                                        a 15.9155 15.9155 0 0 1 0 -31.831"
                  fill="none"
                  stroke="#e6e6e6"
                  strokeWidth="3"
                  strokeDasharray="100, 100"
                ></path>
                <path
                  d="M18 2.0845
                                        a 15.9155 15.9155 0 0 1 0 31.831
                                        a 15.9155 15.9155 0 0 1 0 -31.831"
                  fill="none"
                  stroke="#4CAF50"
                  strokeWidth="3"
                  strokeDasharray="78, 100"
                  className="progress-ring__circle"
                ></path>
              </svg>
              <div className="absolute inset-0 flex items-center justify-center text-xs font-bold text-gray-700">
                78%
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
        <div className="space-y-6 lg:col-span-2">
          <div className="rounded-lg bg-white p-6 shadow">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-800">Upload Training Records</h3>
              <button className="text-blue-600 hover:text-blue-800">
                <i className="fas fa-question-circle"></i>
              </button>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg border-2 border-dashed border-gray-300 p-6 text-center">
                <i className="fas fa-file-excel mb-3 text-4xl text-green-600"></i>
                <p className="mb-3 text-gray-600">Drag &amp; drop your Excel file here or click to browse</p>
                <input type="file" id="file-upload" className="hidden" accept=".xlsx,.xls,.csv" />
                <label
                  htmlFor="file-upload"
                  className="inline-block cursor-pointer rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-700"
                >
                  Select File
                </label>
                <p className="mt-2 text-xs text-gray-500">Supported formats: .xlsx, .xls, .csv</p>
              </div>
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <i className="fas fa-plug text-blue-500"></i>
                  <span className="text-sm text-gray-600">Connect to LMS/TryBooking API</span>
                </div>
                <button className="rounded-md bg-gray-100 px-4 py-2 text-sm text-gray-700 hover:bg-gray-200">
                  Configure API
                </button>
              </div>
            </div>
          </div>

          <div className="rounded-lg bg-white p-6 shadow">
            <div className="mb-4 flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-800">Recent Training Activities</h3>
              <button className="text-sm text-blue-600 hover:text-blue-800">View All</button>
            </div>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase">
                      Training
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase">
                      Type
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase">
                      Date
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium tracking-wider text-gray-500 uppercase">
                      Status
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200 bg-white">
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-blue-100">
                          <i className="fas fa-laptop-code text-blue-600"></i>
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900">Workplace Safety</div>
                          <div className="text-sm text-gray-500">12 participants</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap text-gray-500">LMS</td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap text-gray-500">May 15, 2023</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex rounded-full bg-green-100 px-2 text-xs leading-5 font-semibold text-green-800">
                        Completed
                      </span>
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-purple-100">
                          <i className="fas fa-users text-purple-600"></i>
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900">First Aid Training</div>
                          <div className="text-sm text-gray-500">8 participants</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap text-gray-500">F2F</td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap text-gray-500">May 18, 2023</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex rounded-full bg-yellow-100 px-2 text-xs leading-5 font-semibold text-yellow-800">
                        Pending
                      </span>
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center">
                        <div className="flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-full bg-red-100">
                          <i className="fas fa-fire-extinguisher text-red-600"></i>
                        </div>
                        <div className="ml-4">
                          <div className="text-sm font-medium text-gray-900">Fire Safety</div>
                          <div className="text-sm text-gray-500">24 participants</div>
                        </div>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap text-gray-500">LMS</td>
                    <td className="px-6 py-4 text-sm whitespace-nowrap text-gray-500">May 20, 2023</td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="inline-flex rounded-full bg-green-100 px-2 text-xs leading-5 font-semibold text-green-800">
                        Completed
                      </span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-800">Quick Actions</h3>
            <div className="space-y-3">
              <button className="flex w-full items-center justify-between rounded-md bg-blue-50 px-4 py-3 text-blue-700 hover:bg-blue-100">
                <span>Create New Training</span>
                <i className="fas fa-plus"></i>
              </button>
              <button className="flex w-full items-center justify-between rounded-md bg-green-50 px-4 py-3 text-green-700 hover:bg-green-100">
                <span>Generate Compliance Report</span>
                <i className="fas fa-file-pdf"></i>
              </button>
              <button className="flex w-full items-center justify-between rounded-md bg-purple-50 px-4 py-3 text-purple-700 hover:bg-purple-100">
                <span>Send Reminders</span>
                <i className="fas fa-bell"></i>
              </button>
            </div>
          </div>

          <div className="rounded-lg bg-white p-6 shadow">
            <h3 className="mb-4 text-lg font-semibold text-gray-800">Training Compliance</h3>
            <div className="space-y-3">
              <div>
                <div className="mb-1 flex justify-between text-sm">
                  <span>Workplace Safety</span>
                  <span>85%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-gray-200">
                  <div className="h-2 w-[85%] rounded-full bg-blue-600"> </div>
                </div>
              </div>
              <div>
                <div className="mb-1 flex justify-between text-sm">
                  <span>First Aid</span>
                  <span>72%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-gray-200">
                  <div className="h-2 w-[72%] rounded-full bg-green-600"></div>
                </div>
              </div>
              <div>
                <div className="mb-1 flex justify-between text-sm">
                  <span>Fire Safety</span>
                  <span>91%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-gray-200">
                  <div className="h-2 w-[91%] rounded-full bg-red-600"></div>
                </div>
              </div>
              <div>
                <div className="mb-1 flex justify-between text-sm">
                  <span>Emergency Procedures</span>
                  <span>64%</span>
                </div>
                <div className="h-2 w-full rounded-full bg-gray-200">
                  <div className="h-2 w-[64%] rounded-full bg-purple-600"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
